Removed duplicated spdlog dependency and modified building instruction
intel/ad-rss-lib pull request #117
Opened 2021-11-23 16:46 UTC by mdrwiega

Checklist:

  - [x] Your branch is up-to-date with the `master` branch and tested with latest changes
  - [x] Extended the README / documentation, if necessary
  - [x] Code compiles correctly and runs
  - [x] Code is formatted using clang-3.9 and the provided format file
  - [x] Changelog is updated

#### Description

The `spdlog` is added to `ad-rss-lib` as dependency and it's added to `carla_simulator/map` that is also the dependency of `ad-rss-lib`.
Because of that, it's not possible to update submodules recursively.

In this PR, the `spdlog` dependency is removed from `ad-rss-lib`, so only one version remains in `carla_simulator/map`.
It allows adding the `ad-rss-lib` to other packages (especially ROS2 packages) as dependency and updating dependencies with --recursive option.

Fixes #116

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Library version:**4.5.0

#### Possible Drawbacks

2021-11-23 17:50 UTC, berndgassmann requested changes
Thanks very much for the changes.
I believe we have to adapt the .github workflows from
  with:
    submodules: true
to
  with:
    submodules: recursive

to make the github builds clean.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/117#-:-MpCuMyt-9PBm_SR8xNS:bhu8926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mdrwiega)



<!-- Sent from Reviewable.io -->

2021-11-23 18:18 UTC, mdrwiega commented
Sorry, I forgot to update the workflow configuration.
And thanks for pointing this out.

I have just switched the mode in `actions/checkout` to `recursive` (apart from `code_format_check.yml`).

2021-11-24 07:25 UTC, berndgassmann commented
Thanks again for updating the PR. I have just triggered PR #118 to get rid of the remaining problem in the above runs as the PROJ was removed in map already at the latest revision.

2021-11-24 11:04 UTC, berndgassmann approved these changes
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mdrwiega)



<!-- Sent from Reviewable.io -->

2021-11-24 11:05 UTC, merged

2021-11-24 11:06 UTC, berndgassmann commented
Thanks again for proving the input